### PR TITLE
YuktabaGohil_002786959

### PR DESCRIPTION
**Pull request by Yuktagohil**
Solved Question2 and Question 3. Have some confusion in Question1.

### CODE REVIEW

**Comment by pranavk1511** [comment]
Please go over the assignment once again carefully

**Comment by Yuktagohil** [comment]
Hey

Can you provide more detail?
On Why I need to go over the assignment once again.
I tried making pull request just to learn how to do that.
Also, I have only completed 2 questions.
Is there anything that is not correct?
________________________________

**Comment by pranavk1511** [comment]
From a glance, I think you are trying to solve the questions given in the pdf for the first assignment, whereas the assignment is to design your own questions, their answers and explanations to the answers . You need to change the file accordingly. The pull request looks fine , just follow the naming convention mentioned in the file .

**Comment by Yuktagohil** [comment]
I think I have different questions. The concept is same but the questions are different.
Can you please look and confirm?
I thik the questions are not the same. Chatgpt just gave me something similar to that and not the same.
Am I doing it wrong?
Please confirm and let me know as I have completed almost eight questions of the assignment like this.
________________________________

**Comment by pranavk1511** [comment]
You can proceed, just don't have the same exact questions. Closing the pull request for now

**Pull request closed without merging**
