### PR TITLE
002688252_Zijian_Feng:"Finished Assigment 1"

### PR DESCRIPTION
**Pull request by Fxhj0501**
002688252_Zijian_Feng : "finished assignment one"

### CODE REVIEW

**Comment by pranavk1511** [comment]
Follow the naming conventions for the pull request . Please change the title.

**Comment by Fxhj0501** [comment]
I have changed the title of the pull request. If there still have questions, please just let me know.

**Comment by pranavk1511** [comment]
Github Wise Submission looks good. If you have time, work on the content, and elaborate on it.

**Comment by Fxhj0501** [comment]
Do you mean I should explain more for each question on Assignment 1?

**Comment by pranavk1511** [comment]
> Do you mean I should explain more for each question on Assignment 1?

Yess

**Comment by Fxhj0501** [comment]
I have added more details to my assignment and uploaded the final version of my assignment. If there still has some format problems, please just let me know.

**Pull request merged**
